
language: c

dist: bionic
os: linux
arch:
 - amd64
 - ppc64le

addons:
  apt:
    packages:
      - intltool
      - libglib2.0-dev
      - libgtk-3-dev
      - libgtksourceview-3.0-dev
      - libpoppler-glib-dev
      - libgtkspell3-3-dev
      - libsynctex-dev
    update: true

script:
      - ./autogen.sh
      - ./configure
      - make
